FIND_PATH(LBFGS_INCLUDE_DIR lbfgs.h /usr/include /usr/local/include)

FIND_LIBRARY(LBFGS_LIBRARY NAMES liblbfgs.a PATHS /usr/lib /usr/local/lib)


IF (LBFGS_INCLUDE_DIR AND LBFGS_LIBRARY)
   SET(LBFGS_FOUND TRUE)
ENDIF (LBFGS_INCLUDE_DIR AND LBFGS_LIBRARY)


IF (LBFGS_FOUND)
   IF (NOT LBFGS_FIND_QUIETLY)
      MESSAGE(STATUS "Found LBFGS headers: ${LBFGS_INCLUDE_DIR}")
      MESSAGE(STATUS "Found LBFGS library: ${LBFGS_LIBRARY}")
   ENDIF (NOT LBFGS_FIND_QUIETLY)
ELSE (LBFGS_FOUND)
   IF (LBFGS_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Cound not find LBFGS")
   ENDIF (LBFGS_FIND_REQUIRED)
ENDIF (LBFGS_FOUND)
